@startuml RetriveNoteScreen - Class
title RetriveNoteScreen - Class 
package Pages{
    package RetrieveNoteScreen{
        class RetrieveNoteScreen{
            - _retrieveNoteScreenVM : RetrieveNoteScreenVM
            + initState() : void
            + dispose() : void
        }
        class RetrieveNoteScreenVM{
            + navigateToHomeScreen() : void
            + navigateToFailureScreen() : void 
            + retrieveNotesFromService() : Future<void>
            + sortNotesBO() : void
        }
        class RetrieveNoteScreenModel{
            + sharedPreferenceService : IPlatformSharedPreferenceService
            + @originalListOfNotesBO : List<NotesBO>
            + @tempListOfNotesBO : List<NotesBO>
            + @pageDetailsBO : PageDetailsBO
        }
    }
}
package PlatformService{
    package PlatformSharedPreferenceService{
        interface IPlatformSharedPreferenceService{
            + retrieveNote(key: String): Future<ServiceResult<T?>>
        }
    }
}
package BOs{
    package PageDetailsBO{
        class PageDetailsBO{
        }
    }
}
package BOs{
    package NotesBO{
        class NotesBO{
        }
        class NotesBOSortExtension{
            + sortTitleInAscending() : List<NotesBO>
        }
    }
}
RetrieveNoteScreenVM --> PageDetailsBO 
RetrieveNoteScreen --> RetrieveNoteScreenVM : uses
RetrieveNoteScreenVM --> RetrieveNoteScreenModel : extends
RetrieveNoteScreenVM --> IPlatformSharedPreferenceService 
RetrieveNoteScreenVM --> NotesBOSortExtension 
NotesBOSortExtension --> NotesBO
RetrieveNoteScreenVM --> NotesBO 

