@startuml RetrieveNoteScreenVM - Sequence - Pseudo 
!define POSITIVERESPONSE 90EE90

!define NEGATIVEERESPONSE EFBBBB

!define NUETRALRESPONSE F2DC79

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE

    LifeLineBackgroundColor #E7E8D1

    LifeLineBorderColor #2C5F2D

    ActorBackgroundColor #FC766AFF

    ActorBorderColor #FC766AFF

    ArrowColor #B85042

    ArrowFontColor #234E70

}

title RetrieveNoteScreenVM - retrieveNotesFromService()
autonumber 1
hide footbox 
Caller -> RetrieveNoteScreenVM : Invoke **retrieveNotesFromService()**
activate Caller 
activate RetrieveNoteScreenVM 
alt  (TRY)
    RetrieveNoteScreenVM -> platformSharedPreferenceService : Invoke **retrieveNote(key: String)** 
    activate platformSharedPreferenceService 
    platformSharedPreferenceService --> RetrieveNoteScreenVM : Returns the **ServiceResult<T?>**
    deactivate platformSharedPreferenceService 
    RetrieveNoteScreenVM -> RetrieveNoteScreenVM : Assign the **ServiceResult<T?>** in a variable **responseRetrieved** 
    alt #POSITIVERESPONSE (reponseReceived.statuscode == 200)
        RetrieveNoteScreenVM -> RetrieveNoteScreenVM : Assign the **responseReceived.content** to a variable **@originalListOfNotesBO** and **@tempListOfNotesBO**
    else #NEGATIVEERESPONSE
        RetrieveNoteScreenVM -> RetrieveNoteScreenVM : Set the status code and status of page to the instance of **PageDetailsBO** and assign it to **@pageDetailsBO** 
        RetrieveNoteScreenVM -> RetrieveNoteScreenVM : Invoke **navigateToFailureScreen()** 
        RetrieveNoteScreenVM --> Caller : Returns 
end

else #NEGATIVEERESPONSE (CATCH)
    RetrieveNoteScreenVM -> RetrieveNoteScreenVM : Write log exceptions
    RetrieveNoteScreenVM -> RetrieveNoteScreenVM : Set the status code and status of page to the instance of **PageDetailsBO** and assign it to **@pageDetailsBO** 
    RetrieveNoteScreenVM -> RetrieveNoteScreenVM : Invoke **navigateToFailureScreen()** 
    RetrieveNoteScreenVM --> Caller : Returns 
    deactivate RetrieveNoteScreenVM
    deactivate Caller
end 

==PSEUDOCODE - retrieveNotesFromService()==
hnote across 
    **TRY**

        INVOKE **retrieveNote(key: String)** and pass **1** as the value of the **key**

        ASSIGN the **ServiceResult<T?>** to the variable **responseRetrieved** 

            **IF (responseReceived.statuscode == 200)**

                ASSIGN the **responseReceived.content** to a variable **@originalListOfNotesBO** and **@tempListOfNotesBO**

            **ELSE** 

                SET the **response.statuscode** as statusCode and **"Retrieve"** as pageData to instance of **PageDetailsBO** and set the instance to **@pageDetailsBO**

                Invoke **navigateToFailureScreen()** and **@pageStatus** is passed as extradata to the page 

    **CATCH** 

        INVOKE **writeExceptionData()** on the exception object as **ex**

        SET the **response.statuscode** as statusCode and **"Retrieve"** as pageData to instance of **PageDetailsBO** and set the instance to **@pageDetailsBO**

        INVOKE **navigateToFailureScreen()** 
end hnote 

newpage RetrieveNoteScreenVM - navigateToHomeScreen() 
autonumber 1 
hide footbox 
Caller -> RetrieveNoteScreenVM : Invoke **navigateToHomeScreen()**
alt #POSITIVERESPONSE (TRY)
activate Caller 
activate RetrieveNoteScreenVM 
RetrieveNoteScreenVM -> RetrieveNoteScreenVM : Navigate to **HomeScreen**
RetrieveNoteScreenVM --> Caller : Returns 
else #NEGATIVEERESPONSE (CATCH)
RetrieveNoteScreenVM -> RetrieveNoteScreenVM : Write log exceptions
RetrieveNoteScreenVM --> Caller : Returns
deactivate Caller 
deactivate RetrieveNoteScreenVM 
end 

==PSEUDOCODE - navigateToHomeScreen()== 
hnote across 
    **TRY**

        ADD the event **navigatorPush** to the **navigationStream** object along with parameter **(pageconfig: HomeScreen.pageconfig, data: null) 
    
    **CATCH** 

        INVOKE **writeExceptionData()** on the exception object **ex**
end hnote

newpage RetrieveNoteScreenVM - navigateToFailureScreen()
autonumber 1
hide footbox  
Caller -> RetrieveNoteScreenVM : Invoke **navigateToFailureScreen()** 
activate Caller 
activate RetrieveNoteScreenVM 
alt #POSITIVERESPONSE (TRY)
RetrieveNoteScreenVM -> RetrieveNoteScreenVM : Navigate to **ProcessFailedScreen**
RetrieveNoteScreenVM --> Caller : Returns 
else #NEGATIVEERESPONSE (CATCH)
RetrieveNoteScreenVM -> RetrieveNoteScreenVM : Write log exceptions
RetrieveNoteScreenVM --> Caller : Returns
deactivate Caller 
deactivate RetrieveNoteScreenVM 
end 

==PSEUDOCODE- navigateToFailureScreen()== 
hnote across 
    **TRY**

        ADD the event **navigatorPush** to the **navigationStream** object with parameter **(pageconfig: ProcessFailedScreen.pageconfig, data: @pageDetailsBO)**

    **CATCH** 

        INVOKE **writeExceptionData()** on the exception object **ex**
end hnote 

newpage sortNotesBO()
autonumber 1 
hide footbox 
Caller -> RetrieveNoteScreenVM : Invoke **sortNotesBO()**
activate Caller 
activate RetrieveNoteScreenVM
alt #POSITIVERESPONSE (TRY)
RetrieveNoteScreenVM -> UserBOExtension : Invoke **@tempListOfNotesBO.sortTitleInAscending()**
activate UserBOExtension
UserBOExtension --> RetrieveNoteScreenVM : Returns
deactivate UserBOExtension 
RetrieveNoteScreenVM -> RetrieveNoteScreenVM : Set the returned value in **@tempListOfNotesBO**
RetrieveNoteScreenVM --> Caller : Returns 
else #NEGATIVEERESPONSE (CATCH) 
RetrieveNoteScreenVM -> RetrieveNoteScreenVM : Write log exceptions
RetrieveNoteScreenVM --> Caller : Returns
deactivate Caller 
deactivate RetrieveNoteScreenVM 
end 

==PSEUDOCODE-  sortNotesBO()== 
hnote across 
    **TRY**
        Invoke **@tempListOfNotesBO.sortTitleInAscending()** in UserBOExtension

        SET the returned list in **@tempListOfNotesBO**

    **CATCH** 

        Invoke **writeExceptionData()** on the exception object **ex**

end hnote 