@startuml RetrieveNoteScreen - Sequence - Pseudo 
!define POSITIVERESPONSE 90EE90

!define NEGATIVEERESPONSE EFBBBB

!define NUETRALRESPONSE F2DC79

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE

    LifeLineBackgroundColor #E7E8D1

    LifeLineBorderColor #2C5F2D

    ActorBackgroundColor #FC766AFF

    ActorBorderColor #FC766AFF

    ArrowColor #B85042

    ArrowFontColor #234E70

}

title RetrieveNoteScreen - initState() 
autonumber 1
hide footbox 
User -> RetrieveNoteScreen : Invoke **initState()** 
activate User 
activate RetrieveNoteScreen 
alt #POSITIVERESPONSE (TRY)
RetrieveNoteScreen -> RetrieveNoteScreen : Invoke **retrieveNotesFromService()**
RetrieveNoteScreen -> RetrieveNoteScreen : Start the **navigationStream** to listen
    alt #POSITIVERESPONSE (event is NavigatorPush)
        RetrieveNoteScreen -> RetrieveNoteScreen : Push the **RetrieveNoteScreen.pageconfig** as pageconfig
    end
    RetrieveNoteScreen --> User : Displays the RetrieveNoteScreen page
else #NEGATIVEERESPONSE (CATCH) 
RetrieveNoteScreen -> RetrieveNoteScreen : Write log exceptions 
RetrieveNoteScreen --> User : Returns 
deactivate User 
deactivate RetrieveNoteScreen
end 

==PSEUDOCODE - initState() ==
hnote across 
**TRY**

    Invoke **initState()**

    Invoke **retrieveNotesFromService()** in the **RetrieveNoteScreenVM** 

    LISTEN to the **navigationStream** 

    **IF event is NavigatorPush** 

        PUSH the **RetrieveNoteScreen.pageconfig** as pageconfig 

        DISPLAY the RetrieveNoteScreen page to the user 

**CATCH**

    INVOKE **writeExceptionData()** on the exception object **ex**
end hnote 

newpage RetrieveNoteScreen - "Go back" button.clicked
autonumber 1
hide footbox 
User -> RetrieveNoteScreen : "Go back" button.clicked
activate User 
activate RetrieveNoteScreen 
RetrieveNoteScreen -> RetrieveNoteScreenVM : Invokes **navigateToHomeScreen()**
activate RetrieveNoteScreenVM
RetrieveNoteScreenVM --> RetrieveNoteScreen : Returns 
deactivate RetrieveNoteScreenVM 
RetrieveNoteScreen --> User : Returns 
deactivate User 
deactivate RetrieveNoteScreen 

==PSEUDOCODE - "Go back" button.clicked==
hnote across 
    CLICKS **Go back** button

    INVOKE **navigateToHomeScreen()**
end hnote 

newpage RetrieveNoteScreen - "sort" button.clicked
autonumber 1
hide footbox 
User -> RetrieveNoteScreen : "sort" button.clicked
activate User 
activate RetrieveNoteScreen 
RetrieveNoteScreen -> RetrieveNoteScreenVM : Invokes **sortNotesBO()**
activate RetrieveNoteScreenVM
RetrieveNoteScreenVM --> RetrieveNoteScreen : Returns 
deactivate RetrieveNoteScreenVM 
RetrieveNoteScreen --> User : Returns 
deactivate User 
deactivate RetrieveNoteScreen 

==PSEUDOCODE - "Go back" button.clicked==
hnote across 
    CLICKS **Go back** button

    INVOKE **sortNotesBO()**
end hnote 

newpage RetrieveNoteScreen - dispose()
autonumber 1
hide footbox 
User -> RetrieveNoteScreen : Invoke **dispose()** 
activate User 
activate RetrieveNoteScreen
RetrieveNoteScreen -> RetrieveNoteScreen : Dispose the instance of **RetrieveNoteScreenVM** 
RetrieveNoteScreen --> User : Returns 
deactivate User 
deactivate RetrieveNoteScreen

==PSEUDOCODE - dispose()==
hnote across 
    INVOKE **dispose()** 

    DISPOSE the instance of *RetrieveNoteScreenVM** 
end hnote 