@startuml ProcessFailedScreen - Class 
title ProcessFailedScreen - Class 
package Pages{
    package ReusableView{
        package ProcessFailedScreen{
            class ProcessFailedScreen{
                - _processFailedScreenVM : ProcessFailedScreenVM
                + initState() : void 
                + dispose() : void
            }
            class ProcessFailedScreenVM{
                + displayTheFailureReason(pageStatus : Map ) : void 
                + navigateToHomeScreen() : void 
            }
            class ProcessFailedScreenModel{
                + @pageTitle : String 
                + @statusOfProcess : String 
                + @statusCode : String
            }
        }
    }
}
ProcessFailedScreen --> ProcessFailedScreenVM : uses 
ProcessFailedScreenVM --> ProcessFailedScreenModel : extends 

@enduml