@startuml CreateNoteScreen-Sequence-Pseudo
!define POSITIVERESPONSE 90EE90

!define NEGATIVEERESPONSE EFBBBB

!define NUETRALRESPONSE F2DC79

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE

    LifeLineBackgroundColor #E7E8D1

    LifeLineBorderColor #2C5F2D

    ActorBackgroundColor #FC766AFF

    ActorBorderColor #FC766AFF

    ArrowColor #B85042

    ArrowFontColor #234E70

}
title CreateNoteScreen - initState() 
autonumber 1 
hide footbox 
User -> CreateNoteScreen : Invoke **initState()** 
activate User 
activate CreateNoteScreen 
alt  (TRY)
    CreateNoteScreen -> CreateNoteScreen : Start the stream **titleFieldController** to listen 
    alt #POSITIVERESPONSE (event is addText)
        CreateNoteScreen -> CreateNoteScreen : Assign the event's data in **titleFieldController**
        CreateNoteScreen -> CreateNoteScreen : Collapse the selection 
        CreateNoteScreen --> User : Display the text in the title field
    end
    CreateNoteScreen -> CreateNoteScreen : Start the stream **descriptionFieldController** to listen 
    alt #POSITIVERESPONSE (event is addText)
        CreateNoteScreen -> CreateNoteScreen : Assign the event's data in **descriptionFieldController**
        CreateNoteScreen -> CreateNoteScreen : Collapse the selection 
        CreateNoteScreen --> User : Display the text in the description field
    end 
    CreateNoteScreen -> CreateNoteScreen : Start the **navigationStream** to listen 
    alt #POSITIVERESPONSE (event is NavigatorPush)
        CreateNoteScreen -> CreateNoteScreen : Push the **pageconfig** and the event's **data**
        alt (If Note is created)
            CreateNoteScreen --> User : Display the Note Created Success Screen
        else #NEGATIVEERESPONSE (If creation of note is unsuccessfull)
            CreateNoteScreen --> User : Display the Process Failed Screen
        end
    else (event is NavigatorPop)
        CreateNoteScreen -> CreateNoteScreen : Pop the **pageconfig** and the event's data is checkmounted 
        CreateNoteScreen --> User : Display the Home Screen
    end
else #NEGATIVEERESPONSE (CATCH)
    CreateNoteScreen -> CreateNoteScreen : Write exception logs 
    CreateNoteScreen --> User : Returns 
    deactivate User 
deactivate CreateNoteScreen
end 
 

==PSEUDOCODE - initState() == 
hnote across 

**TRY**

    LISTEN to the stream **titleFieldController** 

    **IF event == addText** 

        SET the event's data to the **titleFieldController** text 

        COLLAPSE the selection and provide the **titleFieldController** text length in **offset**

        DISPLAY the text in the title input field 

    LISTEN to the stream **descriptionFieldController** 
    
    **IF event == addText** 

        SET the event's data to the **descriptionFieldController** text 

        COLLAPSE the selection and provide the **descriptionFieldController** text length in **offset**

        DISPLAY the text in the description input field 
    
    LISTEN to the stream **navigationStream** 

    **IF event == NavigatorPush** 

        PUSH the event's **pageconfig** and the **event's data**
    
    **IF event == NavigatorPop** 

        POP the event's **pageconfig** and the event is checkmounted 

**CATCH**
    
    INVOKE **writeExceptionData()** on the exception object **ex**
end hnote 

newpage CreateNoteScreen - User types in title field 
autonumber 1 
hide footbox 
User -> CreateNoteScreen : Enters text in **title** field 
activate User 
activate CreateNoteScreen
CreateNoteScreen -> CreateNoteScreenVM : Invokes **onChangeTitle(title : String)**
activate CreateNoteScreenVM
CreateNoteScreenVM --> CreateNoteScreen : Returns
deactivate CreateNoteScreenVM  
CreateNoteScreen --> User : Returns 
deactivate CreateNoteScreen 
deactivate User 

==PSEUDOCODE - User types in title field==
hnote across 
    TYPES on the **title** field 

    INVOKES **onChangeTitle(title : String)**
end hnote 

newpage CreateNoteScreen - User types in description field 
autonumber 1 
hide footbox 
User -> CreateNoteScreen : Enters text in **description** field 
activate User 
activate CreateNoteScreen
CreateNoteScreen -> CreateNoteScreenVM : Invokes **onChangeDescription(description : String)**
activate CreateNoteScreenVM
CreateNoteScreenVM --> CreateNoteScreen : Returns
deactivate CreateNoteScreenVM  
CreateNoteScreen --> User : Returns 
deactivate CreateNoteScreen 
deactivate User 

==PSEUDOCODE - User types in title field==
hnote across 
    TYPES on the **description** field 

    INVOKES **onChangeDescription(title : String)**
end hnote 

newpage CreateNoteScreen - "Create" button.clicked
autonumber 1
hide footbox 
User -> CreateNoteScreen : "Create" button.clicked
activate User 
activate CreateNoteScreen 
CreateNoteScreen -> CreateNoteScreenVM : Invokes **createNoteInService()**
activate CreateNoteScreenVM
CreateNoteScreenVM --> CreateNoteScreen : Returns 
deactivate CreateNoteScreenVM 
CreateNoteScreen --> User : Returns 
deactivate User 
deactivate CreateNoteScreen 

==PSEUDOCODE - "Create" button.clicked==
hnote across 
    CLICKS **Create** button

    INVOKE **createNoteInService()**
end hnote 

newpage CreateNoteScreen - "Go back" button.clicked
autonumber 
hide footbox 
User -> CreateNoteScreen : "Go back" button.clicked
activate User 
activate CreateNoteScreen 
CreateNoteScreen -> CreateNoteScreenVM : Invokes **navigateToHomeScreen()**
activate CreateNoteScreenVM
CreateNoteScreenVM --> CreateNoteScreen : Returns 
deactivate CreateNoteScreenVM 
CreateNoteScreen --> User : Returns 
deactivate User 
deactivate CreateNoteScreen 

==PSEUDOCODE - "Create" button.clicked==
hnote across 
    CLICKS **Go back** button

    INVOKE **navigateToHomeScreen()**
end hnote 

newpage CreateNoteScreen - dispose()
autonumber 1 
hide footbox 
User -> CreateNoteScreen : Invoke **dispose()**
activate User 
activate CreateNoteScreen 
CreateNoteScreen-> CreateNoteScreen : Dispose the **titleFieldController**
CreateNoteScreen -> CreateNoteScreen : Dispose the **descriptionFieldController** 
CreateNoteScreen --> User : Returns 
deactivate User 
deactivate CreateNoteScreen 

==PSEUDOCODE - dispose()==
hnote across 
    DISPOSE the **titleFieldController**

    DISPOSE the **descriptionFieldController** 
end hnote 