@startuml CreateNoteScreen - Class 
title CreateNoteScreen - Class 
package Pages{
    package CreateNoteScreen{
        class CreateNoteScreen{
            - _createNoteScreenVM : CreateNoteScreenVM
            + initState() : void 
            + dispose() : void 
        }
        class CreateNoteScreenVM{
            + createNoteInService() : Future<void>
            + navigateToSuccessScreen() : void 
            + navigateToFailureScreen() : void 
            + navigateToHomeScreen() : void 
            + onChangeTitle(title : String) : void 
            + onChangeDescription(description: String) : void
        }
        class CreateNoteScreenModel{
            + sharedPreferenceService : IPlatformSharedPreferenceService
            + @id : int
            + @title : String 
            + @description : String 
            + @pageStatus : Map 
            + @listOfNotesBO : List<NotesBO>
        }
    }
}
package Services{
    package PlatformService{
        package PlatformSharedPreferenceService{
            interface IPlatformSharedPreferenceService{
                + createNote(key: int, value: List<NotesBO>) : Future<ServiceResult<bool>>
            }
        }
    }
}
package BOs{
    package NotesBO{
        class NotesBO{
        }
    }
}
CreateNoteScreen --> CreateNoteScreenVM : uses
CreateNoteScreenVM --> IPlatformSharedPreferenceService 
CreateNoteScreenVM --> NotesBO 
CreateNoteScreenVM --> CreateNoteScreenModel : extends
