@startuml CreateNoteScreenVM - Sequence - Pseudo
!define POSITIVERESPONSE 90EE90

!define NEGATIVEERESPONSE EFBBBB

!define NUETRALRESPONSE F2DC79

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE

    LifeLineBackgroundColor #E7E8D1

    LifeLineBorderColor #2C5F2D

    ActorBackgroundColor #FC766AFF

    ActorBorderColor #FC766AFF

    ArrowColor #B85042

    ArrowFontColor #234E70

}


title CreateNoteScreenVM - createNoteInService()
autonumber 1
hide footbox
Caller -> CreateNoteScreenVM : Invoke **createNoteInService()**
activate Caller
activate CreateNoteScreenVM
alt  (TRY)
    CreateNoteScreenVM -> CreateNoteScreenVM : Assign and increment the **@id**
    CreateNoteScreenVM -> CreateNoteScreenVM : In the variable **instanceOfNotesBO** pass the instance of **NotesBO** and assign the value of **@id** , **@title** and **@description** 
    CreateNoteScreenVM -> CreateNoteScreenVM : In the variable **@listOfNotesBO** add the **instanceOfNotesBO**
    CreateNoteScreenVM -> PlatformSharedPreferenceService : Invoke **createNote(key: "1", value: List<NotesBO>)**
    activate PlatformSharedPreferenceService
    PlatformSharedPreferenceService --> CreateNoteScreenVM : Returns the **serviceResult<bool>**
    deactivate PlatformSharedPreferenceService 
    alt #POSITIVERESPONSE (response == true)
        CreateNoteScreenVM -> CreateNoteScreenVM : Invoke **navigateToSuccessScreen()**
        CreateNoteScreenVM --> Caller : Returns
    else #NEGATIVEERESPONSE
        CreateNoteScreenVM -> CreateNoteScreenVM : Set the status code and status of page to the instance of **PageDetailsBO** and assign it to **@pageDetailsBO** 
        CreateNoteScreenVM -> CreateNoteScreenVM :Invoke **navigateToFailureScreen()**
        CreateNoteScreenVM --> Caller : Returns 
    end
    deactivate PlatformSharedPreferenceService 

else #NEGATIVEERESPONSE (CATCH)
        CreateNoteScreenVM -> CreateNoteScreenVM : Write exception logs
        CreateNoteScreenVM -> CreateNoteScreenVM : Set the status code and status of page to the instance of **PageDetailsBO** and assign it to **@pageDetailsBO** 
        CreateNoteScreenVM -> CreateNoteScreenVM : Invoke **navigateToFailureScreen()** 
        CreateNoteScreenVM --> Caller : Returns 
    deactivate CreateNoteScreenVM
    deactivate Caller
end

==PSEUDOCODE - createNoteInService()==
hnote across 
    **TRY** 

        INCREMENT by one and assign it as the value of **@id**

        SET the value of **@id** , **@title** and **@description** in the instance of NotesBO and assign the instance in a variable **instanceOfNotesBO**

        SET the value of **instanceOfNotesBO** to the **@listOfNotesBO**

        INVOKE **createNote(key: "1", value: List<NotesBO>)** in the **PlatformSharedPreferenceService**, where **@listOfNotesBO** is passed as value 

        SET the **serviceResult<bool>** to **response** 

        **IF (response.content == true)**

            INVOKE **navigateToSuccessScreen()**
        
        **ELSE** 

            SET the **response.statuscode** as statusCode and **"Creation"** as pageData to instance of **PageDetailsBO** and set the instance to **@pageDetailsBO**

            INVOKE **navigateToFailureScreen()** 

    **CATCH** 

        INVOKE **writeExceptionData()** on the exception object **ex**

        SET the **response.statuscode** as statusCode and **"Creation"** as pageData to instance of **PageDetailsBO** and set the instance to **@pageDetailsBO**

        INVOKE **navigateToFailureScreen()** 
end hnote

newpage CreateNoteScreenVM - navigateToSuccessScreen() 
autonumber 1
hide footbox 
Caller -> CreateNoteScreenVM : Invoke **navigateToSuccessScreen()** 
activate Caller 
activate CreateNoteScreenVM 
alt #POSITIVERESPONSE (TRY)
CreateNoteScreenVM -> CreateNoteScreenVM : Navigate to **NoteCreatedSuccessScreen**
CreateNoteScreenVM --> Caller : Returns 
else #NEGATIVEERESPONSE (CATCH)
CreateNoteScreenVM -> CreateNoteScreenVM : Write exception logs 
CreateNoteScreenVM --> Caller : Returns
deactivate CreateNoteScreenVM 
deactivate Caller
end


==PSEUDOCODE - navigateToSuccessScreen()== 
hnote across 
    **TRY**

        ADD the event **navigatorPush** to the **navigationStream** object along with **parameter (pageconfig: NoteCreatedSuccessScreen.pageconfig, data: @pageDetailsBO)**
    
    **CATCH** 

        INVOKE **writeExceptionData()** on the exception object **ex**
end hnote 

newpage CreateNoteScreenVM - navigateToHomeScreen()
autonumber 1
hide footbox 
Caller -> CreateNoteScreenVM : Invoke **navigateToHomeScreen()**
activate Caller 
activate CreateNoteScreenVM 
alt #POSITIVERESPONSE (TRY)
CreateNoteScreenVM -> CreateNoteScreenVM : Navigate to **HomeScreen**
CreateNoteScreenVM --> Caller : Returns 
else #NEGATIVEERESPONSE (CATCH)
CreateNoteScreenVM -> CreateNoteScreenVM : Write exception logs 
CreateNoteScreenVM --> Caller : Returns
deactivate CreateNoteScreenVM 
deactivate Caller 
end

==PSEUDOCODE - navigateToHomeScreen()== 
hnote across 
    **TRY**
        
        ADD the event **navigatorPop** to the **navigationStream** object 
    
    **CATCH** 

        INVOKE **writeExceptionData()** on the exception object **ex**
end hnote 

newpage CreateNoteScreenVM - navigateToFailureScreen() 
autonumber 1
hide footbox 
Caller -> CreateNoteScreenVM : Invoke **navigateToFailureScreen()** 
activate Caller 
activate CreateNoteScreenVM 
alt #POSITIVERESPONSE (TRY)
CreateNoteScreenVM -> CreateNoteScreenVM : Navigate to **ProcessFailedScreen**
CreateNoteScreenVM --> Caller : Returns 
else #NEGATIVEERESPONSE (CATCH)
CreateNoteScreenVM -> CreateNoteScreenVM : Write exception logs 
CreateNoteScreenVM --> Caller : Returns
deactivate CreateNoteScreenVM 
deactivate Caller 
end 

==PSEUDOCODE - navigateToFailureScreen() == 
hnote across 
    **TRY**
        
        ADD the event **navigatorPush** to the **navigationStream** object along with the **parameter (pageconfig: ProcessFailedScreen., data: @pageDetailsBO)**     
    
    **CATCH** 

        INVOKE **writeExceptionData()** on the exception object **ex**
end hnote 

newpage CreateNoteScreenVM - onChangeTitle()
autonumber 1
hide footbox
Caller -> CreateNoteScreenVM : Invoke **onChangeTitle(title : String)**
activate Caller
activate CreateNoteScreenVM
alt #POSITIVERESPONSE (TRY)
CreateNoteScreenVM -> CreateNoteScreenVM : Add the **title** to the **titleFieldController** stream
CreateNoteScreenVM -> CreateNoteScreenVM : Set the value got from **title** to **@title**
CreateNoteScreenVM --> Caller : Returns
else #NEGATIVEERESPONSE (CATCH)
CreateNoteScreenVM -> CreateNoteScreenVM : Write exception logs 
CreateNoteScreenVM --> Caller : Returns
deactivate CreateNoteScreenVM 
deactivate Caller
end

==PSEUDOCODE - onChangeTitle()==
hnote across
    **TRY**

        ADD the **title** from the parameter to the event of the stream **titleFieldController**

        SET the value of the parameter **title** to **@title**
    
    **CATCH** 

        INVOKE **writeExceptionData()** on the exception object **ex**
end hnote

newpage CreateNoteScreenVM - onChangeDescription()
autonumber 1
hide footbox
Caller -> CreateNoteScreenVM : Invoke **onChangeDescription(description : String)**
activate Caller
activate CreateNoteScreenVM
alt #POSITIVERESPONSE (TRY)
CreateNoteScreenVM -> CreateNoteScreenVM : Add the **description** to the **descriptionFieldController** stream
CreateNoteScreenVM -> CreateNoteScreenVM : Set the value got from description to **@description**
CreateNoteScreenVM --> Caller : Returns
else #NEGATIVEERESPONSE (CATCH)
CreateNoteScreenVM -> CreateNoteScreenVM : Write exception logs 
CreateNoteScreenVM --> Caller : Returns
deactivate CreateNoteScreenVM 
deactivate Caller
end 

==PSEUDOCODE - onChangeDescription()==
hnote across
    **TRY**

        ADD the **description** to the event of the stream **descriptionFieldController**

        SET the value of the parameter **description** to **@description**
    
    **CATCH** 

        INVOKE **writeExceptionData()** on the exception object **ex**
end hnote