@startuml NoteCreatedSuccessfulScreen - class 
title NoteCreatedSuccessfulScreen - class 
package Pages{
    package NoteCreatedSuccessScreen{
        class NoteCreatedSuccessScreen{
            - _noteCreatedSuccessScreenVM : NoteCreatedSuccessfullScreenVM
            + initStatus() : void  
            + dispose() : void  
        }
        class NoteCreatedSuccessScreenVM{
            + navigateToHomeScreen() : void 
        }   
        class NoteCreatedSuccessScreenModel{
    }
}
}

NoteCreatedSuccessScreen --> NoteCreatedSuccessScreenVM : uses
NoteCreatedSuccessScreenVM --> NoteCreatedSuccessScreenModel : extends

@enduml